export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";

export const GET_PAGE_TITLE = "GET_PAGE_TITLE";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const PLAGIARISM_ONLINE = "PLAGIARISM_ONLINE";
export const PLAGIARISM_ONLINE_INPUT = "PLAGIARISM_ONLINE_INPUT";

//Activity
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const ACTIVITY_LOADING = "ACTIVITY_LOADING";

// Colleges
export const GET_COLLEGES = "GET_COLLEGES";
export const GET_COLLEGE = "GET_COLLEGE";
export const COLLEGE_LOADING = "COLLEGE_LOADING";
export const CHANGE_BUTTON_STATUS_COLLEGE = "CHANGE_BUTTON_STATUS_COLLEGE";
export const CHANGE_STATUS_COLLEGE = "CHANGE_STATUS_COLLEGE";

// Research
export const GET_RESEARCHES = "GET_RESEARCHES";
export const GET_RESEARCH = "GET_RESEARCH";
export const RESEARCH_LOADING = "RESEARCH_LOADING";
export const CHANGE_BUTTON_STATUS_RESEARCH = "CHANGE_BUTTON_STATUS_RESEARCH";
export const CHANGE_STATUS_RESEARCH = "CHANGE_STATUS_RESEARCH";

// JOURNAL
export const GET_JOURNALS = "GET_JOURNALS";
export const GET_JOURNAL = "GET_JOURNAL";
export const JOURNAL_LOADING = "JOURNAL_LOADING";
export const CHANGE_BUTTON_STATUS_JOURNAL = "CHANGE_BUTTON_STATUS_JOURNAL";
export const CHANGE_STATUS_JOURNAL = "CHANGE_STATUS_JOURNAL";
